---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  namespace: openshift-storage
  name: ocs-storagecluster
spec:
  flexibleScaling: true
  storageDeviceSets:
  - name: ocs-deviceset
    count: 3
    replica: 1
    resources: {}
    placement: {}
    dataPVCTemplate:
      spec:
        storageClassName: null
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 1Ti
    portable: false
